### ISSUE TITLE
Unable to download NCo Connectors

### ISSUE THREAD

**Issue by YaseenZub** [airbus-seclab/powersap#3]
Hi, I am trying to learn SAP applications pentesting. We have an upcoming client that uses SAP heavily. However, I am unable to download the NCo connector as it requires a license which I am unable to obtain. Can I get some help here?

**Comment by Sn0rkY** [comment]
NCo connectors can be downloaded over the SAP portal https://support.sap.com/en/product/connectors/msnet.html and redistribution without license is protected by SAP. We can't deliver NCo on their behalf, sorry.
